
import database.MethodsUser;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mauro
 */
public class Delete extends javax.swing.JFrame {

    private final int adminId;
    private final String adminName;
    MethodsUser object = new MethodsUser();

    /**
     * Creates new form delete
     *
     * @param adminId
     * @param adminName
     */
    public Delete(int adminId, String adminName) {
        initComponents();
        setIcon();

        this.adminId = adminId;
        this.adminName = adminName;
        List<String> cadena = object.allContacts(adminId);

        DefaultTableModel model = (DefaultTableModel) tblConsultDelete.getModel();

        model.setRowCount(0);

        for (String contactDetails : cadena) {
            String[] rowData = contactDetails.split("\n");
            model.addRow(rowData);
        }

        tblConsultDelete.setModel(model);
        jScrollPane1.setViewportView(tblConsultDelete);

        tblConsultDelete.setRowHeight(40);
    }

    private Delete() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteMenu = new javax.swing.JButton();
        txtDeleteEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultDelete = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        fondo_delete = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeleteMenu.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnDeleteMenu.setBorder(null);
        btnDeleteMenu.setContentAreaFilled(false);
        btnDeleteMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 50, 30));

        txtDeleteEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtDeleteEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDeleteEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtDeleteEmail.setBorder(null);
        txtDeleteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtDeleteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 260, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tblConsultDelete.setBackground(new java.awt.Color(204, 204, 204));
        tblConsultDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tblConsultDelete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobre Nome", "E-mail", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblConsultDelete.setRowHeight(30);
        jScrollPane1.setViewportView(tblConsultDelete);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 610, 260));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setContentAreaFilled(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 130, 40));

        fondo_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DELETAR_CONTATO.jpg"))); // NOI18N
        getContentPane().add(fondo_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMenuActionPerformed
        MainMenu newFrame = new MainMenu(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteMenuActionPerformed

    private void txtDeleteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteEmailActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String email = txtDeleteEmail.getText();
            object.deleteContact(email, adminId);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique se o contato que você deseja excluir existe");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Delete().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JLabel fondo_delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsultDelete;
    private javax.swing.JTextField txtDeleteEmail;
    // End of variables declaration//GEN-END:variables
	private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
