import database.MethodsUser;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author mauro
 */
public class InsertProd extends javax.swing.JFrame {

    private final int adminId;
    private final String adminName;

    /**
     * Creates new form insert
     *
     * @param adminId
     * @param adminName
     */
    public InsertProd(int adminId, String adminName) {
        initComponents();
        setIcon();
        
        this.adminId = adminId;
        this.adminName = adminName;
    }

    private InsertProd() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertMenu = new javax.swing.JButton();
        txtInsertCity = new javax.swing.JTextField();
        txtInsertGender = new javax.swing.JTextField();
        txtInsertName = new javax.swing.JTextField();
        txtInsertAge_range = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInsertMenu.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertMenu.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnInsertMenu.setBorder(null);
        btnInsertMenu.setContentAreaFilled(false);
        btnInsertMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 50, 30));

        txtInsertCity.setBackground(new java.awt.Color(51, 51, 51));
        txtInsertCity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInsertCity.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertCity.setBorder(null);
        getContentPane().add(txtInsertCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 310, 41));

        txtInsertGender.setBackground(new java.awt.Color(51, 51, 51));
        txtInsertGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInsertGender.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertGender.setBorder(null);
        getContentPane().add(txtInsertGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 370, 310, 41));

        txtInsertName.setBackground(new java.awt.Color(51, 51, 51));
        txtInsertName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInsertName.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertName.setBorder(null);
        txtInsertName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtInsertName, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 190, 310, 41));

        txtInsertAge_range.setBackground(new java.awt.Color(51, 51, 51));
        txtInsertAge_range.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInsertAge_range.setForeground(new java.awt.Color(255, 255, 255));
        txtInsertAge_range.setBorder(null);
        txtInsertAge_range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertAge_rangeActionPerformed(evt);
            }
        });
        getContentPane().add(txtInsertAge_range, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 120, 41));

        btnInsert.setBackground(new java.awt.Color(204, 204, 204));
        btnInsert.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnInsert.setBorder(null);
        btnInsert.setContentAreaFilled(false);
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 140, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ADICIONAR PROD.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMenuActionPerformed
        MainMenu newFrame = new MainMenu(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertMenuActionPerformed

    private void txtInsertAge_rangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertAge_rangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertAge_rangeActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            MethodsUser object = new MethodsUser();
            String name = txtInsertName.getText();
            String age_range = txtInsertAge_range.getText();
            String gender = txtInsertGender.getText();
            String city = txtInsertCity.getText();
            if (object.addProd(name, age_range, city, gender, adminId)) {
                JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso");
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtInsertNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InsertProd().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsertMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtInsertAge_range;
    private javax.swing.JTextField txtInsertCity;
    private javax.swing.JTextField txtInsertGender;
    private javax.swing.JTextField txtInsertName;
    // End of variables declaration//GEN-END:variables
	private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }

}
