/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class MainMenu extends javax.swing.JFrame {

    private final int adminId;
    private final String adminName;

    /**
     * Creates new form mainMenu
     * @param adminId
     * @param adminName
     */
    public MainMenu(int adminId, String adminName) {
        initComponents();
        this.adminId=adminId;
        this.adminName=adminName;
        lblTextHello.setText("Olá "+adminName+ " O que você gostaria de fazer?");
    }

    private MainMenu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextMainMenu = new javax.swing.JLabel();
        lblTextHello = new javax.swing.JLabel();
        btnConsultContacts = new javax.swing.JButton();
        btnConsultOne = new javax.swing.JButton();
        btnUpdateContact = new javax.swing.JButton();
        btnInsertContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbxItem = new javax.swing.JComboBox<>();
        btnInsertContact2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartManager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextMainMenu.setFont(new java.awt.Font("Century Schoolbook", 3, 18)); // NOI18N
        lblTextMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblTextMainMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextMainMenu.setText("Main Menu");
        getContentPane().add(lblTextMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, 29));

        lblTextHello.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTextHello.setForeground(new java.awt.Color(255, 255, 255));
        lblTextHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextHello.setText("O quê gostaria de fazer?");
        getContentPane().add(lblTextHello, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 393, -1));

        btnConsultContacts.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultContacts.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnConsultContacts.setText("Consultar todos os clentes");
        btnConsultContacts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnConsultContacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultContactsActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        btnConsultOne.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultOne.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnConsultOne.setText("Consultar um cliente");
        btnConsultOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnConsultOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultOneActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 30));

        btnUpdateContact.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnUpdateContact.setText("Atualizar cadastro");
        btnUpdateContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUpdateContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 30));

        btnInsertContact.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnInsertContact.setText("Adicionar cliente");
        btnInsertContact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnInsertContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 170, 30));

        btnDeleteContact.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteContact.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteContact.setText("Excluir um cliente");
        btnDeleteContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 30));

        btnLogout.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnLogout.setText("Menu Principal");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jButton1.setText("SORTEAR");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        cbxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemActionPerformed(evt);
            }
        });
        getContentPane().add(cbxItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        btnInsertContact2.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertContact2.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnInsertContact2.setText("Adicionar produto");
        btnInsertContact2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnInsertContact2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertContact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContact2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultContactsActionPerformed
        SelectAll newFrame=new SelectAll(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultContactsActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        Delete newFrame=new Delete(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteContactActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        Main newFrame = new Main();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInsertContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContactActionPerformed
        Insert newFrame=new Insert(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertContactActionPerformed

    private void btnUpdateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateContactActionPerformed
        Update newFrame=new Update(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateContactActionPerformed

    private void btnConsultOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultOneActionPerformed
        SelectOne newFrame=new SelectOne(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultOneActionPerformed

    private void cbxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItemActionPerformed

    private void btnInsertContact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContact2ActionPerformed
        Insert newFrame=new Insert(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnInsertContact2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultContacts;
    private javax.swing.JButton btnConsultOne;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnInsertContact;
    private javax.swing.JButton btnInsertContact2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdateContact;
    private javax.swing.JComboBox<String> cbxItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTextHello;
    private javax.swing.JLabel lblTextMainMenu;
    // End of variables declaration//GEN-END:variables
}
