/**
 *
 * @author mauro
 */
import database.Conection;
import database.MethodsUser;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Main() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtLoginEmail = new javax.swing.JTextField();
        txtLoginPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoginRegister.setBackground(new java.awt.Color(153, 153, 153));
        btnLoginRegister.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnLoginRegister.setBorder(null);
        btnLoginRegister.setContentAreaFilled(false);
        btnLoginRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoginRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 140, 50));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 140, 50));

        txtLoginEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLoginEmail.setBorder(null);
        txtLoginEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLoginEmail.setDoubleBuffered(true);
        txtLoginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 270, 30));

        txtLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLoginPassword.setBorder(null);
        txtLoginPassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLoginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGIN.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginRegisterActionPerformed
        Conection newConn = new Conection();
        newConn.getConnection();

        Registro newFrame = new Registro();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
            
            try {
            MethodsUser object = new MethodsUser();
            String email = txtLoginEmail.getText();
            String password=String.valueOf (txtLoginPassword.getPassword());
            
            if (object.login(email, password)) {
                int adminId;
                String adminName;
                adminId = 0;
                adminName = "";
                adminId = object.getId(email, password);
                adminName = object.getName(email, password);
                MainMenu newFrame = new MainMenu(adminId, adminName);
                newFrame.setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Verifique se os campos foram preenchidos corretamente");
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Verifique se os campos foram preenchidos corretamente");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginEmailActionPerformed

    private void txtLoginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginPasswordKeyPressed
// USAR TECLA ENTER PARA LOGAR
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
           try {
            MethodsUser object = new MethodsUser();
            String email = txtLoginEmail.getText();
            String password=String.valueOf (txtLoginPassword.getPassword());
            
            if (object.login(email, password)) {
                int adminId;
                String adminName;
                adminId = 0;
                adminName = "";
                adminId = object.getId(email, password);
                adminName = object.getName(email, password);
                MainMenu newFrame = new MainMenu(adminId, adminName);
                newFrame.setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Verifique se os campos foram preenchidos corretamente");
            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Verifique se os campos foram preenchidos corretamente");
        }
    }//GEN-LAST:event_txtLoginPasswordKeyPressed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtLoginEmail;
    private javax.swing.JPasswordField txtLoginPassword;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
