
import java.awt.Toolkit;

/**
 *
 * @author mauro
 */
public class MainMenu extends javax.swing.JFrame {

    private final int adminId;
    private final String adminName;

    /**
     * Creates new form mainMenu
     *
     * @param adminId
     * @param adminName
     */
    public MainMenu(int adminId, String adminName) {
        initComponents();
        setIcon();
        
        this.adminId = adminId;
        this.adminName = adminName;
        lblTextHello.setText("Olá " + adminName + "! Seja bem vindo ao Smartmanager!");
    }

    private MainMenu() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextHello = new javax.swing.JLabel();
        btnConsultContacts = new javax.swing.JButton();
        btnConsultOne = new javax.swing.JButton();
        btnUpdateContact = new javax.swing.JButton();
        btnInsertContact = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnInsertContact2 = new javax.swing.JButton();
        btnSorteio = new javax.swing.JButton();
        btnGanhadores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTextHello.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTextHello.setForeground(new java.awt.Color(255, 255, 255));
        lblTextHello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextHello.setText("O quê gostaria de fazer?");
        getContentPane().add(lblTextHello, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 780, -1));

        btnConsultContacts.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultContacts.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnConsultContacts.setBorder(null);
        btnConsultContacts.setContentAreaFilled(false);
        btnConsultContacts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultContacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultContactsActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultContacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 200, 50));

        btnConsultOne.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultOne.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnConsultOne.setBorder(null);
        btnConsultOne.setContentAreaFilled(false);
        btnConsultOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultOneActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 160, 40));

        btnUpdateContact.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdateContact.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUpdateContact.setBorder(null);
        btnUpdateContact.setContentAreaFilled(false);
        btnUpdateContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 160, 40));

        btnInsertContact.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertContact.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnInsertContact.setBorder(null);
        btnInsertContact.setContentAreaFilled(false);
        btnInsertContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 160, 40));

        btnDeleteContact.setBackground(new java.awt.Color(0, 0, 0));
        btnDeleteContact.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteContact.setBorder(null);
        btnDeleteContact.setContentAreaFilled(false);
        btnDeleteContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteContactActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 160, 40));

        btnLogout.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 30, 30));

        btnInsertContact2.setBackground(new java.awt.Color(204, 204, 204));
        btnInsertContact2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnInsertContact2.setBorder(null);
        btnInsertContact2.setContentAreaFilled(false);
        btnInsertContact2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertContact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertContact2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 160, 40));

        btnSorteio.setBackground(new java.awt.Color(204, 204, 204));
        btnSorteio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSorteio.setBorder(null);
        btnSorteio.setContentAreaFilled(false);
        btnSorteio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteioActionPerformed(evt);
            }
        });
        getContentPane().add(btnSorteio, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 160, 40));

        btnGanhadores.setBackground(new java.awt.Color(102, 102, 102));
        btnGanhadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGanhadores.setForeground(new java.awt.Color(255, 255, 255));
        btnGanhadores.setBorder(null);
        btnGanhadores.setContentAreaFilled(false);
        btnGanhadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGanhadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanhadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnGanhadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MenuPrincipal.jpg"))); // NOI18N
        jLabel1.setText("GANHADORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultContactsActionPerformed
        SelectAll newFrame = new SelectAll(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultContactsActionPerformed

    private void btnDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteContactActionPerformed
        Delete newFrame = new Delete(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDeleteContactActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

        Main newFrame = new Main();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnInsertContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContactActionPerformed
        Inserir newFrame = new Inserir(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertContactActionPerformed

    private void btnUpdateContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateContactActionPerformed
        Update newFrame = new Update(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateContactActionPerformed

    private void btnConsultOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultOneActionPerformed
        SelectOne newFrame = new SelectOne(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultOneActionPerformed

    private void btnInsertContact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertContact2ActionPerformed
        InsertProd newFrame = new InsertProd(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInsertContact2ActionPerformed

    private void btnSorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteioActionPerformed
        Sorteio newFrame = new Sorteio(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnSorteioActionPerformed

    private void btnGanhadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanhadoresActionPerformed
        Ganhadores newFrame = new Ganhadores(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnGanhadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultContacts;
    private javax.swing.JButton btnConsultOne;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnGanhadores;
    private javax.swing.JButton btnInsertContact;
    private javax.swing.JButton btnInsertContact2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSorteio;
    private javax.swing.JButton btnUpdateContact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTextHello;
    // End of variables declaration//GEN-END:variables
	private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
