
import database.MethodsUser;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mauro
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public Registro() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegisterLogin = new javax.swing.JButton();
        txtRegisterEmail = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JPasswordField();
        txtRegisterName = new javax.swing.JTextField();
        txtRegisterLastName = new javax.swing.JTextField();
        txtRegisterUsername = new javax.swing.JTextField();
        txtRegisterRepeatPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        fondoReguister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegisterLogin.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRegisterLogin.setBorder(null);
        btnRegisterLogin.setContentAreaFilled(false);
        btnRegisterLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegisterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 30, 30));

        txtRegisterEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterEmail.setBorder(null);
        getContentPane().add(txtRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 260, 30));

        txtRegisterPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterPassword.setBorder(null);
        getContentPane().add(txtRegisterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 260, 30));

        txtRegisterName.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterName.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterName.setBorder(null);
        getContentPane().add(txtRegisterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 260, 30));

        txtRegisterLastName.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterLastName.setBorder(null);
        getContentPane().add(txtRegisterLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 220, 30));

        txtRegisterUsername.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterUsername.setBorder(null);
        txtRegisterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegisterUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 250, 30));

        txtRegisterRepeatPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterRepeatPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegisterRepeatPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterRepeatPassword.setBorder(null);
        getContentPane().add(txtRegisterRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, 30));

        btnRegister.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRegister.setBorder(null);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 130, 40));

        fondoReguister.setBackground(new java.awt.Color(0, 0, 0));
        fondoReguister.setForeground(new java.awt.Color(255, 255, 255));
        fondoReguister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CADASTRO_USUARIOS.jpg"))); // NOI18N
        fondoReguister.setText("jLabel1");
        getContentPane().add(fondoReguister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLoginActionPerformed
        Main newFrame = new Main();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            MethodsUser object = new MethodsUser();
            String name = txtRegisterName.getText();
            String last_name = txtRegisterLastName.getText();
            String username = txtRegisterUsername.getText();
            String email = txtRegisterEmail.getText();
            String pass1=String.valueOf (txtRegisterPassword.getPassword());
            String pass2=String.valueOf ( txtRegisterRepeatPassword.getPassword());
            if (!pass1.isEmpty() && pass1.equals(pass2) && object.register(name, last_name, username, email, pass1)) {
                System.out.println(object.getId(email, pass1));
                Main newFrame = new Main();
                newFrame.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Valide se os campos foram preenchidos corretamente");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Valide se os campos foram preenchidos corretamente");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtRegisterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterLogin;
    private javax.swing.JLabel fondoReguister;
    private javax.swing.JTextField txtRegisterEmail;
    private javax.swing.JTextField txtRegisterLastName;
    private javax.swing.JTextField txtRegisterName;
    private javax.swing.JPasswordField txtRegisterPassword;
    private javax.swing.JPasswordField txtRegisterRepeatPassword;
    private javax.swing.JTextField txtRegisterUsername;
    // End of variables declaration//GEN-END:variables
	private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
