
import database.MethodsUser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegisterLogin = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        txtRegisterEmail = new javax.swing.JTextField();
        txtRegisterPassword = new javax.swing.JPasswordField();
        lblRegisterEmail = new javax.swing.JLabel();
        lblRegisterPassword = new javax.swing.JLabel();
        txtRegisterName = new javax.swing.JTextField();
        lblRegisterName = new javax.swing.JLabel();
        txtRegisterLastName = new javax.swing.JTextField();
        lblRegisterLastName = new javax.swing.JLabel();
        txtRegisterUsername = new javax.swing.JTextField();
        lblRegisterUsername = new javax.swing.JLabel();
        txtRegisterRepeatPassword = new javax.swing.JPasswordField();
        lblRegisterRepeatPassword = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        fondoReguister = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartManager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegisterLogin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegisterLogin.setText("Menu Principal");
        btnRegisterLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegisterLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegisterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, 30));

        lblRegister.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("Cadastro de Usuários");
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        txtRegisterEmail.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 318, 217, 41));

        txtRegisterPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtRegisterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 394, 217, 41));

        lblRegisterEmail.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterEmail.setText("E-mail");
        getContentPane().add(lblRegisterEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 296, -1, -1));

        lblRegisterPassword.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterPassword.setText("Senha");
        getContentPane().add(lblRegisterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 371, -1, -1));

        txtRegisterName.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterName.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtRegisterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, 217, 41));

        lblRegisterName.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterName.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterName.setText("Nome");
        getContentPane().add(lblRegisterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 71, -1, -1));

        txtRegisterLastName.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtRegisterLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 168, 217, 41));

        lblRegisterLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblRegisterLastName.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterLastName.setText("Sobrenome");
        getContentPane().add(lblRegisterLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 146, -1, -1));

        txtRegisterUsername.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtRegisterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtRegisterUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 243, 217, 41));

        lblRegisterUsername.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterUsername.setText("Usuário");
        getContentPane().add(lblRegisterUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 221, -1, -1));

        txtRegisterRepeatPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtRegisterRepeatPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterRepeatPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtRegisterRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 470, 217, 41));

        lblRegisterRepeatPassword.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblRegisterRepeatPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterRepeatPassword.setText("Repita a senha");
        getContentPane().add(lblRegisterRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 447, -1, -1));

        btnRegister.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegister.setText("Cadastrar");
        btnRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 100, 30));

        fondoReguister.setBackground(new java.awt.Color(0, 0, 0));
        fondoReguister.setForeground(new java.awt.Color(255, 255, 255));
        fondoReguister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        fondoReguister.setText("jLabel1");
        getContentPane().add(fondoReguister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterLoginActionPerformed
        Main newFrame=new Main();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try{
            MethodsUser object = new MethodsUser();
            String name=txtRegisterName.getText();
            String last_name=txtRegisterLastName.getText();
            String username=txtRegisterUsername.getText();
            String email=txtRegisterEmail.getText();
            String pass1=txtRegisterPassword.getText();
            String pass2=txtRegisterRepeatPassword.getText();
            if ( !pass1.isEmpty() && pass1.equals(pass2) && object.register(name, last_name, username, email, pass1)) {
                System.out.println(object.getId(email, pass1));
                Main newFrame=new Main();
                newFrame.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Valide se os campos foram preenchidos corretamente");  
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Valide se os campos foram preenchidos corretamente");  
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtRegisterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterLogin;
    private javax.swing.JLabel fondoReguister;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegisterEmail;
    private javax.swing.JLabel lblRegisterLastName;
    private javax.swing.JLabel lblRegisterName;
    private javax.swing.JLabel lblRegisterPassword;
    private javax.swing.JLabel lblRegisterRepeatPassword;
    private javax.swing.JLabel lblRegisterUsername;
    private javax.swing.JTextField txtRegisterEmail;
    private javax.swing.JTextField txtRegisterLastName;
    private javax.swing.JTextField txtRegisterName;
    private javax.swing.JPasswordField txtRegisterPassword;
    private javax.swing.JPasswordField txtRegisterRepeatPassword;
    private javax.swing.JTextField txtRegisterUsername;
    // End of variables declaration//GEN-END:variables
}
