
import database.MethodsUser;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class SelectAll extends javax.swing.JFrame {

    private final String adminName;
    private final int adminId;

    /**
     * Creates new form SelectAll
     * @param adminId
     * @param adminName
     */
    public SelectAll(int adminId, String adminName) {
        initComponents(); // Inicialización de componentes

        this.adminId = adminId;
        this.adminName=adminName;
        MethodsUser object = new MethodsUser();
        List<String> cadena = object.allContacts(adminId);

        DefaultTableModel model = (DefaultTableModel) tblUsers.getModel();

        // Limpiar la tabla antes de agregar nuevos datos
        model.setRowCount(0);

        // Agregar filas con los datos de la lista a la tabla
        for (String contactDetails : cadena) {
            String[] rowData = contactDetails.split("\n");
            model.addRow(rowData);
        }

        // Actualizar la tabla dentro del JScrollPane
        tblUsers.setModel(model);
        srlPanel.setViewportView(tblUsers);
        
        tblUsers.setRowHeight(40);
    }

    private SelectAll() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelectAllMenu = new javax.swing.JButton();
        srlPanel = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        lblSelectAll = new javax.swing.JLabel();
        fondoSelectAll = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartManager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelectAllMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnSelectAllMenu.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnSelectAllMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectAllMenu.setText("Menu Principal");
        btnSelectAllMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectAllMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectAllMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        srlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Last name", "Phone Number", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srlPanel.setViewportView(tblUsers);

        getContentPane().add(srlPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 67, 564, 140));

        lblSelectAll.setFont(new java.awt.Font("Century Schoolbook", 3, 36)); // NOI18N
        lblSelectAll.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectAll.setText("Consult all contacts");
        getContentPane().add(lblSelectAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 400, -1));

        fondoSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        fondoSelectAll.setText("jLabel1");
        getContentPane().add(fondoSelectAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 260));

        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        fondo2.setText("jLabel1");
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 0, 480, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAllMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllMenuActionPerformed
        MainMenu newFrame=new MainMenu(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectAllMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectAllMenu;
    private javax.swing.JLabel fondo2;
    private javax.swing.JLabel fondoSelectAll;
    private javax.swing.JLabel lblSelectAll;
    private javax.swing.JScrollPane srlPanel;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
