import database.MethodsUser;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauro
 */
public class SelectOne extends javax.swing.JFrame {

    private final String adminName;
    private final int adminId;

    MethodsUser object = new MethodsUser();

    /**
     * Creates new form SelectOne
     *
     * @param adminId
     * @param adminName
     */
    public SelectOne(int adminId, String adminName) {
        initComponents();
        setIcon();
        
        this.adminId = adminId;
        this.adminName = adminName;
    }

    private SelectOne() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelectOneMenu = new javax.swing.JButton();
        txtConsultEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectOne = new javax.swing.JTable();
        btnSelectOne = new javax.swing.JButton();
        fondoSelectOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SmartManager");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelectOneMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnSelectOneMenu.setFont(new java.awt.Font("Century Schoolbook", 3, 12)); // NOI18N
        btnSelectOneMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectOneMenu.setBorder(null);
        btnSelectOneMenu.setContentAreaFilled(false);
        btnSelectOneMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectOneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectOneMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectOneMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 30, 30));

        txtConsultEmail.setBackground(new java.awt.Color(0, 0, 0));
        txtConsultEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtConsultEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        getContentPane().add(txtConsultEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 260, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblSelectOne.setBackground(new java.awt.Color(51, 51, 51));
        tblSelectOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tblSelectOne.setForeground(new java.awt.Color(255, 255, 255));
        tblSelectOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSelectOne);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 790, 220));

        btnSelectOne.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        btnSelectOne.setBorder(null);
        btnSelectOne.setContentAreaFilled(false);
        btnSelectOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectOneActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 160, 50));

        fondoSelectOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CONSULTAR_USUARIO.jpg"))); // NOI18N
        getContentPane().add(fondoSelectOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectOneMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectOneMenuActionPerformed
        MainMenu newFrame = new MainMenu(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectOneMenuActionPerformed

    private void btnSelectOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectOneActionPerformed
        try {
            String email = txtConsultEmail.getText();
           
            if (!email.isEmpty()) {
                List<String> cadena = object.oneContact(email, adminId);
                DefaultTableModel model = (DefaultTableModel) tblSelectOne.getModel();
                model.setRowCount(0);
                
                for (String contactDetails : cadena) {
                    String[] rowData = contactDetails.split("\n");
                    model.addRow(rowData);
                }
                
                tblSelectOne.setModel(model);
                jScrollPane1.setViewportView(tblSelectOne);
                tblSelectOne.setRowHeight(40);
            
            } else {
                JOptionPane.showMessageDialog(null, "O usuário não existe, tente pesquisar novamente, validando a pesquisa corretamente");
            }
        } catch (HeadlessException e) {

        }
    }//GEN-LAST:event_btnSelectOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SelectOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectOne;
    private javax.swing.JButton btnSelectOneMenu;
    private javax.swing.JLabel fondoSelectOne;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSelectOne;
    private javax.swing.JTextField txtConsultEmail;
    // End of variables declaration//GEN-END:variables
        private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icone.png")));
    }
}
