
import database.MethodsUser;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class Update extends javax.swing.JFrame {

    private final String adminName;
    private final int adminId;
    private int id;

    /**
     * Creates new form Update
     * @param adminId
     * @param adminName
     */
    public Update(int adminId, String adminName) {
        initComponents();
        this.adminId=adminId;
        this.adminName = adminName;
        
        MethodsUser object = new MethodsUser();
        List<String> cadena = object.allContactsUpdate(adminId);

        DefaultTableModel model = (DefaultTableModel) tblConsultUpdate.getModel();

        // Limpiar la tabla antes de agregar nuevos datos
        model.setRowCount(0);

        // Agregar filas con los datos de la lista a la tabla
        for (String contactDetails : cadena) {
            String[] rowData = contactDetails.split("\n");
            model.addRow(rowData);
        }

        // Actualizar la tabla dentro del JScrollPane
        tblConsultUpdate.setModel(model);
        jScrollPane1.setViewportView(tblConsultUpdate);
        
        tblConsultUpdate.setRowHeight(40);
        
        txtUpdateName.setEnabled(false);
        txtUpdateLastName.setEnabled(false);
        txtUpdateEmail.setEnabled(false);
        txtUpdatePhone.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    private Update() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultUpdate = new javax.swing.JTable();
        lblUpdate = new javax.swing.JLabel();
        lblUpdateId = new javax.swing.JLabel();
        txtUpdateId = new javax.swing.JTextField();
        lblUpdateName = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        lblUpdateLastName = new javax.swing.JLabel();
        txtUpdateLastName = new javax.swing.JTextField();
        lblUpdatePhone = new javax.swing.JLabel();
        txtUpdatePhone = new javax.swing.JTextField();
        lblUpdateEmail = new javax.swing.JLabel();
        txtUpdateEmail = new javax.swing.JTextField();
        btnConsultUpdate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        fondoUpdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartManager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdateMenu.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        btnUpdateMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateMenu.setText("Menu Principal");
        btnUpdateMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblConsultUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tblConsultUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Last Name", "Phone Number", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultUpdate);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 490, 140));

        lblUpdate.setFont(new java.awt.Font("Century Schoolbook", 3, 36)); // NOI18N
        lblUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdate.setText("Atualizar Contato");
        getContentPane().add(lblUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 350, -1));

        lblUpdateId.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        lblUpdateId.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateId.setText("ID : ");
        getContentPane().add(lblUpdateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtUpdateId.setBackground(new java.awt.Color(0, 0, 0));
        txtUpdateId.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(txtUpdateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 240, -1));

        lblUpdateName.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        lblUpdateName.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateName.setText("Name : ");
        getContentPane().add(lblUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtUpdateName.setBackground(new java.awt.Color(0, 0, 0));
        txtUpdateName.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(txtUpdateName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 240, -1));

        lblUpdateLastName.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        lblUpdateLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateLastName.setText("Last Name : ");
        getContentPane().add(lblUpdateLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        txtUpdateLastName.setBackground(new java.awt.Color(0, 0, 0));
        txtUpdateLastName.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(txtUpdateLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, -1));

        lblUpdatePhone.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        lblUpdatePhone.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdatePhone.setText("Phone Number : ");
        getContentPane().add(lblUpdatePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txtUpdatePhone.setBackground(new java.awt.Color(0, 0, 0));
        txtUpdatePhone.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdatePhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(txtUpdatePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, 20));

        lblUpdateEmail.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        lblUpdateEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateEmail.setText("Email : ");
        getContentPane().add(lblUpdateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtUpdateEmail.setBackground(new java.awt.Color(0, 0, 0));
        txtUpdateEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(txtUpdateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 210, -1));

        btnConsultUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnConsultUpdate.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        btnConsultUpdate.setText("Coletar dados");
        btnConsultUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConsultUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 120, 30));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        btnUpdate.setText("Atualizar");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 120, 30));

        fondoUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.png"))); // NOI18N
        fondoUpdate.setText("jLabel1");
        getContentPane().add(fondoUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMenuActionPerformed
        MainMenu newFrame=new MainMenu(adminId, adminName);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateMenuActionPerformed

    private void btnConsultUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultUpdateActionPerformed
        try {
            MethodsUser object = new MethodsUser();
            id = Integer.parseInt(txtUpdateId.getText());
            List<String> updateDetails = object.getUpdate(id, adminId);

            if (updateDetails.size() >= 4) {
                txtUpdateName.setText(updateDetails.get(0)); // Asignar el primer elemento a txtUpdateName
                txtUpdateLastName.setText(updateDetails.get(1)); // Asignar el segundo elemento a txtUpdateLastName
                txtUpdateEmail.setText(updateDetails.get(2)); // Asignar el tercer elemento a txtUpdateEmail
                txtUpdatePhone.setText(updateDetails.get(3)); // Asignar el cuarto elemento a txtUpdatePhone

                // Habilitar los text inputs
                txtUpdateName.setEnabled(true);
                txtUpdateLastName.setEnabled(true);
                txtUpdateEmail.setEnabled(true);
                txtUpdatePhone.setEnabled(true);
                btnUpdate.setEnabled(true);
                
            } else {
                JOptionPane.showMessageDialog(null, "A lista não tem elementos suficientes");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Insira um ID válido");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConsultUpdateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            String name=txtUpdateName.getText();
            String lastName = txtUpdateLastName.getText();
            String email= txtUpdateEmail.getText();
            String phone=txtUpdatePhone.getText();
            if (!name.isEmpty() && !email.isEmpty() && !lastName.isEmpty() && !phone.isEmpty()) {
                MethodsUser object = new MethodsUser();
                object.update(id, name, lastName, email, phone, adminId);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultUpdate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateMenu;
    private javax.swing.JLabel fondoUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdateEmail;
    private javax.swing.JLabel lblUpdateId;
    private javax.swing.JLabel lblUpdateLastName;
    private javax.swing.JLabel lblUpdateName;
    private javax.swing.JLabel lblUpdatePhone;
    private javax.swing.JTable tblConsultUpdate;
    private javax.swing.JTextField txtUpdateEmail;
    private javax.swing.JTextField txtUpdateId;
    private javax.swing.JTextField txtUpdateLastName;
    private javax.swing.JTextField txtUpdateName;
    private javax.swing.JTextField txtUpdatePhone;
    // End of variables declaration//GEN-END:variables
}
